In [1]:
import pandas as pd
import numpy as np

## Game giving two math operations from code:+,-,*,**,/,//,% and a bank of numbers
## the simplified side of the equation is given.  Example __*__/__ = 12  and a bank of numbers that 
## go inthe three spots.  There is an stated number of combinations to be found.

##create add matrix
x=np.arange(1,11)
y=np.arange(1,11)
##y=y.reshape()
print(x)
print(y)
Mmult=np.outer(x,y)

##Mplus=np.dot(y,x)
print(Mmult)

yinv=np.reciprocal(y,dtype=float)
Mdiv=np.outer(x,yinv)
print(Mdiv)

Mplus=np.empty((10,10))
Mminus=np.empty((10,10))
for i in range(len(x)):
    for j in range(len(y)):
        Mplus[i,j]=i+j+2
        Mminus[i,j]=i-j      
        
        
print(Mplus)
print(Mminus)

##These are the combos for addition, subtraction, multiplication and division
##Now make a third dimension to multiply by the 1-10 array
##General form is first operation inside parenthesis... then multiplication

##These are going to become 3-D arrays. 

Mplus3=np.empty((10,10,10))
Mminus3=np.empty((10,10,10))
Mdiv3=np.empty((10,10,10))
Mmult3=np.empty((10,10,10))
for i in range(len(x)):
    Mplus3[:,:,i]=Mplus[:,:]*(i+1)
    Mminus3[:,:,i]=Mminus[:,:]*(i+1)
    Mdiv3[:,:,i]=Mdiv[:,:]*(i+1)
    Mmult3[:,:,i]=Mmult[:,:]*(i+1)
    
print(Mplus3)

#tub=['Mplus3','Mminus3','Mmult3','Mdiv3']
#for x in tub:
num=4
result1=np.where(Mplus3==num)
result2=np.where(Mminus3==num)
result3=np.where(Mmult3==num)
result4=np.where(Mdiv3==num)
print(result1)
np.shape(result1)
##print(result2)
##print(result3)
##print(result4)

[ 1  2  3  4  5  6  7  8  9 10]
[ 1  2  3  4  5  6  7  8  9 10]
[[  1   2   3   4   5   6   7   8   9  10]
 [  2   4   6   8  10  12  14  16  18  20]
 [  3   6   9  12  15  18  21  24  27  30]
 [  4   8  12  16  20  24  28  32  36  40]
 [  5  10  15  20  25  30  35  40  45  50]
 [  6  12  18  24  30  36  42  48  54  60]
 [  7  14  21  28  35  42  49  56  63  70]
 [  8  16  24  32  40  48  56  64  72  80]
 [  9  18  27  36  45  54  63  72  81  90]
 [ 10  20  30  40  50  60  70  80  90 100]]
[[ 1.          0.5         0.33333333  0.25        0.2         0.16666667
   0.14285714  0.125       0.11111111  0.1       ]
 [ 2.          1.          0.66666667  0.5         0.4         0.33333333
   0.28571429  0.25        0.22222222  0.2       ]
 [ 3.          1.5         1.          0.75        0.6         0.5
   0.42857143  0.375       0.33333333  0.3       ]
 [ 4.          2.          1.33333333  1.          0.8         0.66666667
   0.57142857  0.5         0.44444444  0.4       ]
 [ 5.       

(3, 4)

(array([0, 0, 1, 2]), array([0, 2, 1, 0]), array([1, 0, 0, 0]))


(3, 4)